language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="7c48cc1c-4c33-4977-a661-a4a488143ec4"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - sestanovov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

# Start PostgreSQL
services:
  - postgresql

# Create a database
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

